Integrate fork sync
LiskHQ/lisk-node pull request #10
Opened 2024-07-01 14:07 UTC by nagdahimanshu

### What was the problem?

This PR resolves #8 

### How was it solved?

- [ ] Integrate fork sync to the CI pipeline
- [ ] Auto approve should be disabled

### How was it tested?

2024-07-01 15:49 UTC, shuse2 commented on .github/workflows/fork-sync.yml
> +          base: development
why are we integrating to the development branch now?

2024-07-02 05:54 UTC, nagdahimanshu commented on .github/workflows/fork-sync.yml
> +          base: development
My understanding from our chat is to integrate `fork-sync` against development branch but I can update it to `main` if it is fine?

2024-07-02 07:11 UTC, sameersubudhi requested changes

2024-07-02 07:11 UTC, sameersubudhi commented on .github/workflows/fork-sync.yml
> +      - uses: tgymnich/fork-sync@v1.8
Why don't we use the latest version? CUrrent latest is [v2.0.10](https://github.com/marketplace/actions/fork-sync).
```suggestion
      - uses: tgymnich/fork-sync
```

2024-07-02 07:11 UTC, sameersubudhi commented on .github/workflows/fork-sync.yml
> +      - uses: tgymnich/fork-sync@v1.8
BTW could you please also check https://github.com/wei/pull and any other available options. `wei/pull` seems to be significantly more popular and widely adopted than `tgymnich/fork-sync`.

2024-07-02 07:52 UTC, sameersubudhi commented on .github/workflows/fork-sync.yml
> +          owner: base-org
```suggestion
          owner: base-org
          repo: node
```

2024-07-02 08:09 UTC, nagdahimanshu commented on .github/workflows/fork-sync.yml
> +          base: development
Updated it to `main` branch

2024-07-02 08:15 UTC, sameersubudhi approved these changes

2024-07-04 07:08 UTC, shuse2 approved these changes

2024-07-04 07:08 UTC, merged